import test from 'node:test';import assert from 'node:assert/strict';import {ENGINE_PROFILES,advancePowertrain} from '../src/audio-dynamics';
test('all 13 cars have an engine profile and genuinely different firing characteristics',()=>{assert.equal(Object.keys(ENGINE_PROFILES).length,13);assert.equal(new Set(Object.values(ENGINE_PROFILES).map(p=>p.family)).size,10);assert.equal(ENGINE_PROFILES.diablo.cylinders,12);assert.equal(ENGINE_PROFILES.r8.cylinders,10);assert.equal(ENGINE_PROFILES.r34.cylinders,6);});
test('shift hysteresis prevents chatter near a boundary and downshifts during braking',()=>{const p={gear:1,rpm:1000,shift:0,cooldown:0},profile=ENGINE_PROFILES['458'];let shifts=0;for(let i=0;i<180;i++)shifts+=Math.abs(advancePowertrain(p,(i%2?49:48)/3.6,1,325,profile,1/60));assert.equal(shifts,1);assert.equal(p.gear,2);for(let i=0;i<60;i++)advancePowertrain(p,30/3.6,0,325,profile,1/60);assert.equal(p.gear,1);assert.ok(p.rpm>=profile.idle&&p.rpm<=profile.redline);});
test('free rev responds to throttle without shifting; stable gear matches across frame rates',()=>{for(const fps of [30,60,120]){const p={gear:1,rpm:850,shift:0,cooldown:0};for(let i=0;i<fps*2;i++)advancePowertrain(p,0,1,325,ENGINE_PROFILES['458'],1/fps,true);assert.equal(p.gear,1);assert.ok(p.rpm>7000);for(let i=0;i<fps*3;i++)advancePowertrain(p,50,1,325,ENGINE_PROFILES['458'],1/fps);assert.equal(p.gear,4);}});

import {ENGINE_BANKS,engineBlend} from '../src/engine-banks';import fs from 'node:fs';import crypto from 'node:crypto';
test('five supercars use separate new assets and no rejected recording',()=>{const types=['458','f40','r8','diablo','mcf1'],files=types.map(t=>ENGINE_BANKS[ENGINE_PROFILES[t].family].file);assert.equal(new Set(files).size,5);assert.ok(!fs.existsSync('public/audio/exotic.wav'));assert.equal(new Set(files.map(f=>crypto.createHash('sha256').update(fs.readFileSync('public/audio/'+f+'.wav')).digest('hex'))).size,5);});
test('mid-RPM samples never stretch into idle and rate remains bounded',()=>{assert.equal(engineBlend(900,3500).sample,0);assert.equal(engineBlend(3500,3500).rate,1);for(const rpm of [0,900,1500,3500,9000,20000]){const b=engineBlend(rpm,3500);assert.ok(b.rate>=.65&&b.rate<=1.8);assert.ok(b.sample>=0&&b.sample<=1);}});

import {highBlend,AUDIO_ASSETS} from '../src/engine-banks';
test('F40 and Veneno fully replace the midrange clip at high RPM without a pitch plateau',()=>{for(const family of ['ferrariF40','lamboV12'] as const){const b=ENGINE_BANKS[family],h=b.high!;assert.equal(highBlend(h.start,h).mix,0);assert.equal(highBlend(h.end,h).mix,1);assert.equal(highBlend(6500,h).mix,1);assert.ok(highBlend(7800,h).rate>highBlend(7200,h).rate);let previous=0;for(let rpm=h.start;rpm<=h.end;rpm+=10){const mix=highBlend(rpm,h).mix;assert.ok(mix>=previous&&mix-previous<.02);previous=mix;}assert.ok(AUDIO_ASSETS.includes(h.file));const wav=fs.readFileSync('public/audio/'+h.file+'.wav');assert.equal(wav.toString('ascii',0,4),'RIFF');}});

test('four six-cylinder cars use eight separate generated layers, not the old Porsche clip',()=>{const files:string[]=[];for(const type of ['p911','r34','supra','m3']){const bank=ENGINE_BANKS[ENGINE_PROFILES[type].family];assert.ok(bank.high);files.push(bank.file,bank.high!.file);assert.equal(highBlend(6500,bank.high).mix,1);}assert.equal(new Set(files).size,8);assert.ok(!AUDIO_ASSETS.includes('six'));assert.equal(new Set(files.map(file=>crypto.createHash('sha256').update(fs.readFileSync('public/audio/'+file+'.wav')).digest('hex'))).size,8);});
