import { chromium } from '@playwright/test';
const browser=await chromium.launch({headless:true,channel:'msedge'});
const page=await browser.newPage({viewport:{width:844,height:390},isMobile:true,hasTouch:true});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(process.env.TEST_URL||'http://127.0.0.1:5173/');
await page.waitForFunction(()=>window.__velocity,null,{timeout:90000});
await page.click('#navSetup');
await page.locator('#downforce').scrollIntoViewIfNeeded();await page.focus('#downforce');
const before=await page.inputValue('#downforce');await page.keyboard.press('ArrowRight');
const after=await page.inputValue('#downforce');if(Number(after)<=Number(before))throw Error('Range keyboard handling failed');
await page.selectOption('#quality','low');await page.selectOption('#mode','endurance');await page.click('#startBtn');
await page.waitForFunction(()=>window.__velocity.snapshot().state==='race',null,{timeout:90000});
await page.keyboard.down('KeyP');await page.waitForFunction(()=>document.querySelector('#telemetry').textContent.includes('补给 7.'),null,{timeout:90000});
await page.waitForFunction(()=>document.querySelector('#msg').textContent==='补给完成',null,{timeout:30000});await page.keyboard.up('KeyP');
const session=await page.context().newCDPSession(page);
const gas=await page.locator('#btnGas').boundingBox(),left=await page.locator('#btnL').boundingBox();
const initial=await page.evaluate(()=>window.__velocity.snapshot());
await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:gas.x+gas.width/2,y:gas.y+gas.height/2,id:1},{x:left.x+left.width/2,y:left.y+left.height/2,id:2}]});
await page.waitForFunction(()=>window.__velocity.snapshot().speed>5,null,{timeout:60000});
const moving=await page.evaluate(()=>window.__velocity.snapshot());
await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
if(Math.abs(moving.heading-initial.heading)<.01)throw Error('Simultaneous steering failed');
console.log(JSON.stringify({range:{before,after},pitService:true,multitouch:{speed:moving.speed,headingChange:moving.heading-initial.heading},errors}));
await browser.close();if(errors.length)process.exitCode=1;
