import { chromium } from '@playwright/test';
import fs from 'node:fs';
fs.mkdirSync('artifacts',{recursive:true});
const browser=await chromium.launch({headless:true,channel:'msedge'});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
await page.goto(process.env.TEST_URL||'http://127.0.0.1:5173/');
await page.waitForFunction(()=>window.__velocity,{timeout:90000});
await page.waitForTimeout(2000);
console.log('MENU',await page.evaluate(()=>window.__velocity.snapshot()));
await page.screenshot({path:'artifacts/garage.png'});
await page.click('#navSetup');await page.selectOption('#quality','balanced');
await page.selectOption('#mode','time');
await page.click('#startBtn');await page.waitForFunction(()=>window.__velocity.snapshot().state==='race',null,{timeout:120000});
await page.keyboard.down('KeyW');await page.waitForFunction(()=>window.__velocity.snapshot().speed>8,null,{timeout:60000});await page.keyboard.up('KeyW');
const moving=await page.evaluate(()=>window.__velocity.snapshot());console.log('DRIVING',moving);if(!(moving.speed>2)||moving.ai!==0)throw Error('Driving/time trial failed');
await page.keyboard.press('Escape');const paused=await page.evaluate(()=>window.__velocity.snapshot());if(!paused.paused)throw Error('Pause failed');
await page.screenshot({path:'artifacts/paused.png'});
await page.click('#quitBtn');await page.selectOption('#mode','endurance');await page.selectOption('#weather','rain');await page.selectOption('#tires','wet');
await page.click('#startBtn');await page.waitForFunction(()=>window.__velocity.snapshot().state==='race',null,{timeout:120000});console.log('ENDURANCE',await page.evaluate(()=>window.__velocity.snapshot()));
await page.screenshot({path:'artifacts/race.png'});
await page.keyboard.press('KeyC');await page.waitForTimeout(500);await page.screenshot({path:'artifacts/cockpit.png'});
await page.keyboard.press('Escape');await page.click('#quitBtn');
await page.click('#navTrack');
for(let i=0;i<12;i++){await page.locator('.trackBtn').nth(i).click();await page.waitForTimeout(150);console.log('TRACK',i,(await page.evaluate(()=>window.__velocity.snapshot())).track);}
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/mobile.png'});
console.log('ERRORS',errors);fs.writeFileSync('artifacts/smoke.json',JSON.stringify({moving,errors},null,2));await browser.close();if(errors.length)process.exitCode=1;
