import type {Setup} from './physics';
export const options:Setup & {quality:string;line:boolean}={mode:'sprint',tires:'sport',assist:'sport',downforce:.4,balance:55,weather:'track',quality:'high',line:true,cornerAssist:true};
try{const saved=JSON.parse(localStorage.getItem('uv3-setup')||'{}');for(const key of ['mode','tires','assist','weather'] as const){const allowed:Record<string,string[]>={mode:['sprint','race','time','endurance'],tires:['sport','soft','wet'],assist:['sport','off'],weather:['track','clear','rain'],quality:['high','balanced','low']};if(allowed[key].includes(saved[key]))(options as any)[key]=saved[key];}if(typeof saved.line==='boolean')options.line=saved.line;if(typeof saved.cornerAssist==='boolean')options.cornerAssist=saved.cornerAssist;for(const [key,min,max] of [['downforce',0,1],['balance',45,65]] as const)if(Number.isFinite(saved[key]))options[key]=Math.max(min,Math.min(max,saved[key]));}catch{}
export class Session {
 laps=1;checkpoints=0;invalid=false;best:number|null=null;key='';pit=0;sectors:number[]=[];lastSector=0;
 start(track:string,car:string){this.laps=options.mode==='endurance'?8:options.mode==='race'?3:options.mode==='time'?3:1;this.checkpoints=0;this.invalid=false;this.sectors=[];this.lastSector=0;this.pit=0;this.key=['handling-v4',options.cornerAssist?'assisted':'manual',track,car,options.tires,options.assist,options.weather,options.downforce,options.balance].join(':');this.best=null;try{const v=Number(localStorage.getItem('uv3-best:'+this.key));if(v>0&&Number.isFinite(v))this.best=v;}catch{}}
 progress(before:number,after:number,time:number){
  for(let n=1;n<=3;n++){const t=n/4;if(before<t&&after>=t&&this.checkpoints===n-1){this.checkpoints=n;this.sectors.push(time-this.lastSector);this.lastSector=time;}}
 }
 complete(time:number){const valid=this.checkpoints===3&&!this.invalid&&time>5;if(valid&&(this.best===null||time<this.best)){this.best=time;try{localStorage.setItem('uv3-best:'+this.key,String(time));}catch{}}this.checkpoints=0;this.invalid=false;this.sectors=[];this.lastSector=0;return valid;}
}
export function mountSetup(onChange:(key:string)=>void){
 const el=document.createElement('section');el.id='setupPanel';el.innerHTML=`<div class="section-kicker">RACE ENGINEERING <span>赛事工程</span></div>
 <label>赛事模式<select id="mode"><option value="sprint">短程冲刺 · 1 圈</option><option value="race">巡回竞速 · 3 圈</option><option value="time">计时挑战 · 3 圈 / 单人</option><option value="endurance">耐力挑战 · 8 圈 / 补给</option></select></label>
 <div class="setup-grid"><label>天气<select id="weather"><option value="track">赛道原生天气</option><option value="clear">晴朗</option><option value="rain">降雨</option></select></label><label>轮胎<select id="tires"><option value="sport">运动胎</option><option value="soft">软质干地胎</option><option value="wet">雨胎</option></select></label><label>驾驶辅助<select id="assist"><option value="sport">运动 · ABS / TCS</option><option value="off">专业 · 关闭辅助</option></select></label><label>画质<select id="quality"><option value="high">最高 · 阴影 / 辉光</option><option value="balanced">均衡</option><option value="low">流畅</option></select></label></div>
 <label>下压力 <output id="aeroValue"></output><input id="downforce" type="range" min="0" max="1" step=".1"></label><label>前轮制动力 <output id="balanceValue"></output><input id="balance" type="range" min="45" max="65" step="1"></label>
 <label class="line-option"><input id="cornerAssist" type="checkbox">弯道减速辅助（建议开启）</label><label class="line-option"><input id="line" type="checkbox">显示弯道制动提示</label><div id="sessionNote"></div>`;
 document.querySelector('#menu')!.append(el);
 const credits=document.createElement('div');credits.className='credits';credits.innerHTML='四条赛道参考真实地理轮廓 · 场景为游戏化还原<br><a href="/circuits/CREDITS.md" target="_blank" rel="noopener">赛道参考与来源</a><br>458 模型：<a href="https://threejs.org/examples/webgl_materials_car.html" target="_blank" rel="noopener">vicent091036 / Three.js</a><br>天空与路面：<a href="https://polyhaven.com" target="_blank" rel="noopener">Poly Haven · CC0</a><br>比赛音效：<a href="/audio/CREDITS.md" target="_blank" rel="noopener">ElevenLabs · 音效来源</a>';document.querySelector('#selPanel')!.append(credits);
 for(const key of Object.keys(options)){const input=document.getElementById(key) as HTMLInputElement;if(!input)continue;if((key==='line'||key==='cornerAssist'))input.checked=Boolean((options as any)[key]);else input.value=String((options as any)[key]);input.addEventListener('change',()=>{(options as any)[key]=(key==='line'||key==='cornerAssist')?input.checked:['downforce','balance'].includes(key)?Number(input.value):input.value;try{localStorage.setItem('uv3-setup',JSON.stringify(options));}catch{}refresh();onChange(key);});}
 function refresh(){document.querySelector('#aeroValue')!.textContent=Math.round(options.downforce*100)+'%';document.querySelector('#balanceValue')!.textContent=options.balance+'%';document.querySelector('#sessionNote')!.textContent=options.mode==='endurance'?'耐力赛：发车区域低于 5 km/h，按住 P 或「补给」8 秒完成加油换胎。':'WASD / 方向键驾驶 · C 切换追尾 / 座舱 / 车头 · Esc 暂停 · R 回正（该圈无效） · 支持手柄 RT / LT';}refresh();
 const telemetry=document.createElement('div');telemetry.id='telemetry';document.querySelector('#hud')!.append(telemetry);
 const pit=document.createElement('button');pit.id='pitButton';pit.textContent='补给 P';document.querySelector('#touchUI')!.append(pit);
}
