import {RaceAudio} from './race-audio';
import {AUDIO_ASSETS} from './engine-banks';
import {CARS} from './cars.js';
const cars=CARS.map(car=>[car.type,car.nameCn]);let selected='458',mode='',audio:RaceAudio,ac:AudioContext,master:GainNode,started=0,last=performance.now();
const status=document.querySelector('#status')!,rpm=document.querySelector('#rpm')!;
function choose(){document.querySelector('#name')!.textContent=cars.find(c=>c[0]===selected)![1];document.querySelectorAll<HTMLButtonElement>('[data-car]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.car===selected)));}
for(const [id,name]of cars){const b=document.createElement('button');b.textContent=name;b.dataset.car=id;b.onclick=()=>{selected=id;started=performance.now();choose();};document.querySelector('#cars')!.append(b);}choose();
document.querySelectorAll<HTMLButtonElement>('[data-mode]').forEach(b=>b.onclick=async()=>{if(!ac){ac=new AudioContext();master=ac.createGain();master.gain.value=Number(document.querySelector<HTMLInputElement>('#volume')!.value)/100;master.connect(ac.destination);audio=new RaceAudio(ac,master);}await ac.resume();mode=b.dataset.mode!;started=performance.now();document.querySelectorAll<HTMLButtonElement>('[data-mode]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));});
function stop(){mode='';audio?.silence();rpm.textContent='—';document.querySelectorAll('[data-mode]').forEach(x=>x.setAttribute('aria-pressed','false'));status.textContent='已停止';}
document.querySelector('#stop')!.addEventListener('click',stop);document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});window.addEventListener('pagehide',stop);
document.querySelector<HTMLInputElement>('#volume')!.oninput=e=>{if(master)master.gain.setTargetAtTime(Number((e.target as HTMLInputElement).value)/100,ac.currentTime,.03);};
function tick(now:number){const dt=Math.min(.1,(now-last)/1000);last=now;if(audio&&mode){const t=(now-started)/1000,throttle=mode==='idle'?0:mode==='mid'?.45:mode==='high'?1:Math.min(1,t/8);audio.update({active:true,type:selected,top:325,speed:0,throttle,brake:0,slip:0,wet:0,camera:0,countdown:true,fuel:100,opponents:[]},dt);const s=audio.snapshot();rpm.textContent=Math.round(s.rpm).toLocaleString();status.textContent=s.failed.length?'部分音源未加载，当前包含合成备用声音':s.loaded.length<AUDIO_ASSETS.length?'正在加载音源…':'正在播放 · '+cars.find(c=>c[0]===selected)![1];}requestAnimationFrame(tick);}requestAnimationFrame(tick);
