import {REVIEW_PROFILES,reviewProfile} from './audio-review/profiles';
import {reviewFrame,type Mode} from './audio-review/model';
import {ReviewEngine} from './audio-review/engine';
import './audio-review/style.css';
import type {RaceAudio} from './audio-review/legacy-race-audio';
import {AUDIO_ASSETS} from './engine-banks';
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
let selected=REVIEW_PROFILES.find(p=>p.id===new URLSearchParams(location.search).get('car'))?.id||'458';
let mode:Mode|''='',ac:AudioContext,master:GainNode,engine:ReviewEngine,legacy:RaceAudio|undefined,version:'new'|'old'='new',start=0,last=0,request=0,ready=false;
let oneShot:AudioBufferSourceNode|undefined;
const records:Record<string,{note:string;approved:boolean}>=(()=>{try{return JSON.parse(localStorage.getItem('velocity-sound-review-v1')||'{}');}catch{return {};}})();
function choose(){const p=reviewProfile(selected);$('name').textContent=p.name;$('engine').textContent=p.engine;$('character').textContent=p.character;$('layout').textContent=p.cylinders+' CYL / '+p.litres.toFixed(1)+' L';$('assumption').textContent=p.note||'';$('assumption').hidden=!p.note;$<HTMLAnchorElement>('source').href=p.source;$<HTMLTextAreaElement>('notes').value=records[selected]?.note||'';$('approve').setAttribute('aria-pressed',String(records[selected]?.approved||false));document.querySelectorAll<HTMLElement>('[data-car]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.car===selected)));}
for(const p of REVIEW_PROFILES){const b=document.createElement('button');b.textContent=p.name;b.dataset.car=p.id;b.onclick=()=>{selected=p.id;choose();if(mode)void play(mode);};$('cars').append(b);}choose();
function init(){if(ac)return;ac=new AudioContext({sampleRate:48000,latencyHint:'interactive'});master=ac.createGain();master.gain.value=Number($<HTMLInputElement>('volume').value)/100;master.connect(ac.destination);engine=new ReviewEngine(ac,master);ac.onstatechange=()=>{if(ac.state!=='running'&&mode)stop();};}
async function play(next:Mode){const ticket=++request;init();ready=false;engine.stop();legacy?.silence();oneShot?.stop();oneShot=undefined;mode=next;$('status').textContent='正在加载所选车辆音源…';document.querySelectorAll<HTMLElement>('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));
 try{await ac.resume();if(version==='new'){if(!await engine.select(reviewProfile(selected)))return;}else if(!legacy){const {RaceAudio}=await import('./audio-review/legacy-race-audio');if(ticket!==request)return;legacy=new RaceAudio(ac,master);}if(version==='old'){const deadline=performance.now()+15000;while(legacy!.snapshot().loaded.length<AUDIO_ASSETS.length){if(ticket!==request)return;if(legacy!.snapshot().failed.length||performance.now()>deadline)throw Error('旧版音源未完整加载，请重试');await new Promise(resolve=>setTimeout(resolve,60));}}if(ticket!==request||document.hidden)return;ready=true;start=last=ac.currentTime;$('status').textContent=version==='new'?'新提案 · 正在试听':'发布前版本 · 正在试听';}catch(e){if(ticket===request){stop();$('status').textContent=e instanceof Error?e.message:'音源加载失败，请重试';}}
}
function stop(){++request;ready=false;mode='';engine?.stop();legacy?.silence();oneShot?.stop();oneShot=undefined;$('rpm').textContent='—';$('level').style.width='0';$('status').textContent='已停止';document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed','false'));}
document.querySelectorAll<HTMLButtonElement>('[data-mode]').forEach(b=>b.onclick=()=>void play(b.dataset.mode as Mode));$('stop').onclick=stop;
$<HTMLInputElement>('volume').oninput=e=>{const v=Number((e.target as HTMLInputElement).value);$('volume-value').textContent=v+'%';if(master)master.gain.setTargetAtTime(v/100,ac.currentTime,.03);};
for(const which of ['new','old'] as const)$(which+'-version').onclick=()=>{version=which;$('wind').toggleAttribute('disabled',which==='old');$('new-version').setAttribute('aria-pressed',String(which==='new'));$('old-version').setAttribute('aria-pressed',String(which==='old'));if(mode)void play(mode);};
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});window.addEventListener('pagehide',stop);
// A fixed control cadence uses audio time, independently of rendering FPS.
setInterval(()=>{if(!ready||!mode||ac.state!=='running')return;const t=ac.currentTime-start,p=reviewProfile(selected),f=reviewFrame(p,mode,t);if(version==='new')engine.update(f,$<HTMLInputElement>('wind').checked);else{legacy!.update({active:true,type:selected,top:325,speed:f.speed,throttle:f.load,brake:0,slip:f.grip,wet:f.wet,camera:0,countdown:f.speed===0,fuel:100,opponents:f.rival?[{x:f.pan*5,z:2,speed:f.speed,type:selected}]:[],surface:{curb:f.curb,grass:f.grass,rough:0,wet:f.wet,tunnel:f.tunnel},grip:f.grip},Math.min(.1,ac.currentTime-last));f.rpm=legacy!.snapshot().rpm;}last=ac.currentTime;$('rpm').textContent=Math.round(f.rpm).toLocaleString();$('speed').textContent=Math.round(f.speed*3.6).toString();$('gear').textContent=f.gear?String(f.gear):'N';$('level').style.width=Math.min(100,f.rpm/p.redline*100)+'%';},25);
function save(){try{localStorage.setItem('velocity-sound-review-v1',JSON.stringify(records));$('saved').textContent='已保存到当前浏览器；复制汇总发给我后再最终确认。';}catch{$('saved').textContent='浏览器未允许保存，请复制意见。';}}
$<HTMLTextAreaElement>('notes').oninput=()=>{records[selected]={note:$<HTMLTextAreaElement>('notes').value,approved:records[selected]?.approved||false};save();};$('approve').onclick=()=>{records[selected]={note:$<HTMLTextAreaElement>('notes').value,approved:!records[selected]?.approved};choose();save();};
$('export').onclick=async()=>{const text=REVIEW_PROFILES.map(p=>`${p.name}：${records[p.id]?.approved?'满意':'待确认'}${records[p.id]?.note?'；'+records[p.id].note:''}`).join('\n');try{await navigator.clipboard.writeText(text);$('saved').textContent='已复制全部车型意见，请发给我。';}catch{$<HTMLTextAreaElement>('notes').value=text;$<HTMLTextAreaElement>('notes').select();$('saved').textContent='请手动复制选中的试听汇总。';}};
document.querySelectorAll<HTMLButtonElement>('[data-sample]').forEach(b=>b.onclick=async()=>{stop();init();const ticket=++request;try{await ac.resume();const r=await fetch('/audio/'+b.dataset.sample+'.wav');if(!r.ok)throw Error();const buffer=await ac.decodeAudioData(await r.arrayBuffer());if(ticket!==request||document.hidden)return;const source=ac.createBufferSource(),g=ac.createGain();source.buffer=buffer;g.gain.value=.3;source.connect(g);g.connect(master);oneShot=source;source.start();source.stop(ac.currentTime+Math.min(3,buffer.duration));source.onended=()=>{source.disconnect();g.disconnect();if(oneShot===source){oneShot=undefined;$('status').textContent='已停止';}};$('status').textContent='现有效果 · '+b.textContent;}catch{$('status').textContent='音源加载失败，请重试';}});




